Repository jmunixusers/cs-vm-build, pull requests merged in 2018-10, with the labels that each got.

#194 Update CS354 packages
  README.md
  roles/robot-pkgs/tasks/main.yml
  roles/robot-pkgs/templates/ros-packages.j2
  roles/robot-pkgs/vars/main.yml
Labels: cs 354, squash and merge

#207 Fix looping style
  roles/adv-prog-pkgs/tasks/main.yml
  roles/adv-prog-pkgs/vars/main.yml
  roles/basic-prog-pkgs/tasks/main.yml
  roles/basic-prog-pkgs/vars/main.yml
  roles/common/handlers/main.yml
  roles/common/tasks/main.yml
  roles/common/vars/main.yml
  roles/drjava/tasks/main.yml
  roles/eclipse/tasks/main.yml
  roles/eclipse/vars/main.yml
  roles/filezilla/tasks/main.yml
  roles/oem/tasks/main.yml
  roles/robot-pkgs/handlers/main.yml
  roles/robot-pkgs/tasks/main.yml
  roles/wireless-printing/tasks/main.yml
  roles/wireless-printing/vars/main.yml
  roles/y86/tasks/main.yml
Labels: squash and merge

#209 Add CS 361 as a separate option
  README.md
  local.yml
  roles/task-shortcuts/files/uug_ansible_wrapper.py
Labels: cs 361, squash and merge

#195 Add script to build a basic Linux Mint appliance
  scripts/create-appliance.sh
Labels: testing required
